/* Generated By:JavaCC: Do not edit this line. Func4ParserConstants.java */
package plp.functional4.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Func4ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 7;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int AND = 9;
  /** RegularExpression Id. */
  int OR = 10;
  /** RegularExpression Id. */
  int NOT = 11;
  /** RegularExpression Id. */
  int LENGTH = 12;
  /** RegularExpression Id. */
  int TRUE = 13;
  /** RegularExpression Id. */
  int FALSE = 14;
  /** RegularExpression Id. */
  int LET = 15;
  /** RegularExpression Id. */
  int VAR = 16;
  /** RegularExpression Id. */
  int IN = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int THEN = 19;
  /** RegularExpression Id. */
  int ELSE = 20;
  /** RegularExpression Id. */
  int FUNC = 21;
  /** RegularExpression Id. */
  int FN = 22;
  /** RegularExpression Id. */
  int HEAD = 23;
  /** RegularExpression Id. */
  int TAIL = 24;
  /** RegularExpression Id. */
  int FOR = 25;
  /** RegularExpression Id. */
  int SELF = 26;
  /** RegularExpression Id. */
  int SPAWN = 27;
  /** RegularExpression Id. */
  int RECEIVE = 28;
  /** RegularExpression Id. */
  int END = 29;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 30;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 31;
  /** RegularExpression Id. */
  int HEX_LITERAL = 32;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 33;
  /** RegularExpression Id. */
  int STRING_LITERAL = 34;
  /** RegularExpression Id. */
  int IDENTIFIER = 35;
  /** RegularExpression Id. */
  int LETTER = 36;
  /** RegularExpression Id. */
  int DIGIT = 37;
  /** RegularExpression Id. */
  int LPAREN = 38;
  /** RegularExpression Id. */
  int RPAREN = 39;
  /** RegularExpression Id. */
  int LBRACE = 40;
  /** RegularExpression Id. */
  int RBRACE = 41;
  /** RegularExpression Id. */
  int LBRACKET = 42;
  /** RegularExpression Id. */
  int RBRACKET = 43;
  /** RegularExpression Id. */
  int SEMICOLON = 44;
  /** RegularExpression Id. */
  int COMMA = 45;
  /** RegularExpression Id. */
  int DOT = 46;
  /** RegularExpression Id. */
  int ARROW = 47;
  /** RegularExpression Id. */
  int ASSIGN = 48;
  /** RegularExpression Id. */
  int GT = 49;
  /** RegularExpression Id. */
  int LT = 50;
  /** RegularExpression Id. */
  int BANG = 51;
  /** RegularExpression Id. */
  int TILDE = 52;
  /** RegularExpression Id. */
  int HOOK = 53;
  /** RegularExpression Id. */
  int EQ = 54;
  /** RegularExpression Id. */
  int LE = 55;
  /** RegularExpression Id. */
  int GE = 56;
  /** RegularExpression Id. */
  int NE = 57;
  /** RegularExpression Id. */
  int SC_OR = 58;
  /** RegularExpression Id. */
  int SC_AND = 59;
  /** RegularExpression Id. */
  int CONCAT = 60;
  /** RegularExpression Id. */
  int CONS = 61;
  /** RegularExpression Id. */
  int CONCAT_LISTA = 62;
  /** RegularExpression Id. */
  int SEQ = 63;
  /** RegularExpression Id. */
  int PLUS = 64;
  /** RegularExpression Id. */
  int MINUS = 65;
  /** RegularExpression Id. */
  int STAR = 66;
  /** RegularExpression Id. */
  int SLASH = 67;
  /** RegularExpression Id. */
  int BIT_AND = 68;
  /** RegularExpression Id. */
  int BIT_OR = 69;
  /** RegularExpression Id. */
  int XOR = 70;
  /** RegularExpression Id. */
  int REM = 71;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"length\"",
    "\"true\"",
    "\"false\"",
    "\"let\"",
    "\"var\"",
    "\"in\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"fun\"",
    "\"fn\"",
    "\"head\"",
    "\"tail\"",
    "\"for\"",
    "\"self\"",
    "\"spawn\"",
    "\"receive\"",
    "\"end\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"->\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\":\"",
    "\"^^\"",
    "\"..\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
  };

}
